# Generated by Django 3.1.6 on 2021-08-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_auto_20210827_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moon',
        ),
    ]
